string Message
string ProgramName
string IpAdress
string ProgramLocation
string Comment
geometry_msgs/Pose[] RobotPoses
bool[] PointColorViz
int32[] IndexVector
---
bool ReturnStatus
string ReturnMessage
