string ProgramLocation
string ProgramName
string Comment
int32 MachiningSpeed
int32 ExtricationSpeed
float64 TrajectoryZOffset
bool Upload
string IpAdress
geometry_msgs/Pose[] RobotPoses
bool[] IsGrindingPose
---
bool ReturnStatus
string ReturnMessage
