bool SurfacingMode
string CADFileName
string ScanFileName
float64 GrinderWidth
uint32 CoveringPercentage
float64 ExtricationRadius
float64 DepthOfPass
bool AngleX
bool AngleY
bool AngleZ
float64 LeanAngle
bool Compute
bool Simulate
---
bool ReturnStatus
string ReturnMessage
geometry_msgs/Pose[] RobotPosesOutput
